#!/usr/bin/env node

/**
 * ShowItGlo — development seed.
 *
 * Creates a small, HONEST dataset: three obviously-fake demo users, six posts
 * that start at exactly zero, and real backing generated by driving
 * store.recordInteraction — so wallets, ledgers, post totals and the board all
 * reconcile the way they would in production.
 *
 * What this script deliberately does NOT do:
 *   * invent raised amounts, backer counts or like counts
 *   * name, impersonate or attribute anything to a real company or person
 *   * create brand responses (a real brand must publish those itself)
 *
 * Usage:
 *   DATABASE_URL="postgresql://user@localhost:5432/showitglo_dev" node scripts/seed-dev.mjs
 *
 * Refuses to run against NODE_ENV=production unless DEMO_SEED=1 is set.
 * Re-running is safe: it detects the demo users and exits without touching
 * anything.
 */

import { existsSync, mkdirSync, readFileSync } from 'fs';
import { createRequire } from 'module';
import { spawnSync } from 'child_process';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const require = createRequire(import.meta.url);

// --------------------------------------------------------------------------
// Environment
// --------------------------------------------------------------------------

function loadDotEnv() {
  for (const envPath of [resolve(repoRoot, '.env.local'), resolve(repoRoot, '.env')]) {
    if (!existsSync(envPath)) continue;
    try {
      for (const line of readFileSync(envPath, 'utf8').split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#') || !trimmed.includes('=')) continue;
        const [k, ...v] = trimmed.split('=');
        const key = k.trim();
        if (!process.env[key]) process.env[key] = v.join('=').trim().replace(/^["']|["']$/g, '');
      }
    } catch {
      /* ignore unreadable env files */
    }
  }
}

loadDotEnv();

if (process.env.NODE_ENV === 'production' && process.env.DEMO_SEED !== '1') {
  console.error('\n❌ Refusing to seed a production environment.');
  console.error('   Set DEMO_SEED=1 if you genuinely intend to write demo data there.\n');
  process.exit(1);
}

if (!process.env.DATABASE_URL) {
  console.error('\n❌ DATABASE_URL is not set.\n');
  console.error('  DATABASE_URL="postgresql://user@localhost:5432/showitglo_dev" node scripts/seed-dev.mjs\n');
  process.exit(1);
}

// --------------------------------------------------------------------------
// Load the real store (compiled from TypeScript so the seed exercises the same
// money code paths the app does, rather than a duplicate written in SQL).
// --------------------------------------------------------------------------

function loadStore() {
  // Must live inside the repo so the compiled CJS resolves `pg` from
  // ./node_modules; node_modules/.cache is already git-ignored.
  const outDir = resolve(repoRoot, 'node_modules/.cache/showitglo-store');
  const tsc = resolve(repoRoot, 'node_modules/.bin/tsc');

  if (!existsSync(tsc)) {
    console.error('\n❌ typescript is not installed. Run `npm install` first.\n');
    process.exit(1);
  }

  mkdirSync(outDir, { recursive: true });

  const result = spawnSync(
    tsc,
    [
      resolve(repoRoot, 'src/lib/db/store.ts'),
      '--outDir', outDir,
      '--rootDir', resolve(repoRoot, 'src/lib'),
      '--module', 'commonjs',
      '--moduleResolution', 'node',
      '--target', 'es2022',
      '--esModuleInterop',
      '--skipLibCheck',
      '--resolveJsonModule',
    ],
    { cwd: repoRoot, stdio: 'inherit' }
  );

  if (result.status !== 0) {
    console.error('\n❌ Could not compile src/lib/db/store.ts.\n');
    process.exit(1);
  }

  return require(resolve(outDir, 'db/store.js'));
}

// --------------------------------------------------------------------------
// Demo fixtures — fixed UUIDs so a re-run recognises its own work.
// --------------------------------------------------------------------------

const DEMO_USERS = [
  { id: '11111111-1111-4111-8111-111111111111', alias: 'Demo Ada (seed)', topupCents: 2000 },
  { id: '22222222-2222-4222-8222-222222222222', alias: 'Demo Bo (seed)', topupCents: 2000 },
  { id: '33333333-3333-4333-8333-333333333333', alias: 'Demo Cy (seed)', topupCents: 2000 },
];

const [ADA, BO, CY] = DEMO_USERS;

const DEMO_POSTS = [
  {
    id: 'aaaaaaa1-0000-4000-8000-000000000001',
    slug: 'seed-remote-work-beats-the-office',
    author: ADA,
    kind: 'opinion',
    title: 'Fully remote teams ship faster than co-located ones',
    body: 'Async written decisions leave a trail. Hallway consensus does not.',
  },
  {
    id: 'aaaaaaa1-0000-4000-8000-000000000002',
    slug: 'seed-the-office-still-wins',
    author: BO,
    kind: 'opinion',
    counterOf: 'aaaaaaa1-0000-4000-8000-000000000001',
    title: 'Nothing replaces a whiteboard and a room full of people',
    body: 'The hardest problems get solved in the twenty minutes after the meeting ends.',
  },
  {
    id: 'aaaaaaa1-0000-4000-8000-000000000003',
    slug: 'seed-tabs-are-correct',
    author: CY,
    kind: 'opinion',
    title: 'Tabs are the only accessible indentation',
    body: 'Readers choose their own width. Spaces take that choice away.',
  },
  {
    id: 'aaaaaaa1-0000-4000-8000-000000000004',
    slug: 'seed-spaces-are-correct',
    author: ADA,
    kind: 'opinion',
    counterOf: 'aaaaaaa1-0000-4000-8000-000000000003',
    title: 'Spaces render identically everywhere, and that is the point',
    body: 'Alignment that survives every editor, terminal and diff view.',
  },
  {
    id: 'aaaaaaa1-0000-4000-8000-000000000005',
    slug: 'seed-city-should-fix-the-night-buses',
    author: BO,
    kind: 'demand',
    demandTarget: 'Demo Transit Authority (fictional)',
    title: 'Run the night buses every 20 minutes instead of every hour',
    body: 'A fictional demand target used only to exercise the demand aggregation code path.',
  },
  {
    id: 'aaaaaaa1-0000-4000-8000-000000000006',
    slug: 'seed-open-source-maintainers-deserve-salaries',
    author: CY,
    kind: 'opinion',
    title: 'Critical open source maintainers should be paid salaries, not tips',
    body: 'Infrastructure that everything depends on should not rest on unpaid weekends.',
  },
];

/** Every backing below is a real transaction: wallet debit + ledger + score. */
const DEMO_BACKINGS = [
  { post: 0, user: BO, kind: 'super', units: 1, cents: 100 },
  { post: 0, user: CY, kind: 'boost', units: 1, cents: 10 },
  { post: 1, user: ADA, kind: 'boost', units: 1, cents: 10 },
  { post: 1, user: CY, kind: 'super', units: 1, cents: 100 },
  { post: 2, user: ADA, kind: 'like', units: 25, cents: 25 },
  { post: 2, user: BO, kind: 'boost', units: 1, cents: 10 },
  { post: 3, user: CY, kind: 'boost', units: 1, cents: 10 },
  { post: 4, user: ADA, kind: 'super', units: 1, cents: 100 },
  { post: 4, user: CY, kind: 'boost', units: 1, cents: 10 },
  { post: 5, user: ADA, kind: 'boost', units: 1, cents: 10 },
  { post: 5, user: BO, kind: 'like', units: 40, cents: 40 },
];

const DEMO_DEBATES = [
  {
    debate: {
      id: 'deb_seed_workplace',
      slug: 'seed-remote-vs-office',
      question: 'Where does a software team actually do its best work?',
      status: 'live',
      curated: true,
      is_political: false,
      category_id: 'global',
      sponsor_user_id: null,
      sponsor_label: null,
    },
    sides: [
      { side_key: 'remote', label: 'Remote-first', post: 0 },
      { side_key: 'office', label: 'In the room', post: 1 },
    ],
    opinions: [
      { side_key: 'remote', author: 'Demo Ada (seed)', text: 'Written decisions outlive the people who made them.' },
      { side_key: 'office', author: 'Demo Bo (seed)', text: 'Half of what I learned came from overhearing it.' },
    ],
  },
  {
    debate: {
      id: 'deb_seed_indentation',
      slug: 'seed-tabs-vs-spaces',
      question: 'Tabs or spaces?',
      status: 'live',
      curated: true,
      is_political: false,
      category_id: 'global',
      sponsor_user_id: null,
      sponsor_label: null,
    },
    sides: [
      { side_key: 'tabs', label: 'Tabs', post: 2 },
      { side_key: 'spaces', label: 'Spaces', post: 3 },
    ],
    opinions: [
      { side_key: 'tabs', author: 'Demo Cy (seed)', text: 'Accessibility beats aesthetics.' },
      { side_key: 'spaces', author: 'Demo Ada (seed)', text: 'Deterministic rendering beats configurability.' },
    ],
  },
];

// --------------------------------------------------------------------------
// Seed
// --------------------------------------------------------------------------

async function main() {
  const store = loadStore();

  console.log('\n🌱 ShowItGlo — development seed');

  const existing = await store.getUser(ADA.id);
  if (existing) {
    console.log('   demo data already present — nothing to do.');
    console.log('   (drop and re-init the database to reseed)\n');
    return;
  }

  const category = await store.getCategory('global');
  if (!category) {
    throw new Error('The "global" category is missing. Run `node scripts/init-db.mjs` first.');
  }

  // 1. Users + wallets. The balance arrives through the same credit path a
  //    real Stripe top-up uses, so the ledger reconciles to the balance.
  for (const user of DEMO_USERS) {
    await store.upsertUser({
      id: user.id,
      email: `devseed_${user.id}@anon.showitglo.local`,
      email_verified_at: null,
      alias: user.alias,
      is_profile_public: true,
      brand_verified_at: null,
      stripe_customer_id: null,
      role: 'user',
      status: 'active',
      notif_prefs: { inapp: true, email: false, push: false, outbid_digest: true },
      created_at: new Date().toISOString(),
      deleted_at: null,
    });

    await store.creditWalletFromPayment({
      userId: user.id,
      amountCents: user.topupCents,
      paymentIntentId: `pi_devseed_${user.id}`,
      currency: 'usd',
    });
  }
  console.log(`   ${DEMO_USERS.length} demo users + funded wallets ✓`);

  // 2. Posts. Every counter starts at zero — nothing is pre-inflated.
  for (const post of DEMO_POSTS) {
    await store.createPost({
      id: post.id,
      slug: post.slug,
      author_id: post.author.id,
      category_id: 'global',
      kind: post.kind,
      title: post.title,
      body: post.body,
      media_url: null,
      is_ad: false,
      demand_target: post.demandTarget ?? null,
      demand_target_user_id: null,
      counter_of: post.counterOf ?? null,
      source_url: null,
      source_platform: null,
      author_display: post.author.alias,
      status: 'live',
      score_base: 0,
      total_raised_cents: 0,
      backers_count: 0,
      like_units: 0,
      streak_days: 0,
    });
  }
  console.log(`   ${DEMO_POSTS.length} posts at zero ✓`);

  // 3. Real backing through the real transaction.
  let spentCents = 0;
  for (const backing of DEMO_BACKINGS) {
    const post = DEMO_POSTS[backing.post];
    await store.recordInteraction({
      postId: post.id,
      userId: backing.user.id,
      kind: backing.kind,
      units: backing.units,
      amountCents: backing.cents,
      visibility: 'alias',
      payerDisplay: backing.user.alias,
      idempotencyKey: `devseed:${post.id}:${backing.user.id}:${backing.kind}`,
    });
    spentCents += backing.cents;
  }
  console.log(`   ${DEMO_BACKINGS.length} backings totalling $${(spentCents / 100).toFixed(2)} ✓`);

  // 4. Debates wired to the posts above.
  for (const entry of DEMO_DEBATES) {
    await store.createDebate(
      { ...entry.debate, created_at: new Date().toISOString() },
      entry.sides.map((side) => ({
        debate_id: entry.debate.id,
        side_key: side.side_key,
        label: side.label,
        post_id: DEMO_POSTS[side.post].id,
      }))
    );

    for (const opinion of entry.opinions) {
      await store.addDebateOpinion({
        debateId: entry.debate.id,
        sideKey: opinion.side_key,
        authorName: opinion.author,
        text: opinion.text,
        isPaid: false,
        amountCents: 0,
      });
    }
  }
  console.log(`   ${DEMO_DEBATES.length} debates ✓`);

  // 5. Report what the board actually looks like now.
  const board = await store.getRankedBoard('global', { limit: 10 });
  console.log('\n   board:');
  for (const row of board) {
    console.log(
      `     #${row.rank}  $${row.display_score.toFixed(2).padStart(6)}  ` +
        `${row.backers_count} backer(s)  ${row.title.slice(0, 52)}`
    );
  }

  const wallets = await Promise.all(DEMO_USERS.map((u) => store.getWallet(u.id)));
  console.log('\n   wallets:');
  for (let i = 0; i < DEMO_USERS.length; i++) {
    const w = wallets[i];
    console.log(
      `     ${DEMO_USERS[i].alias.padEnd(18)} balance $${(w.balance_cents / 100).toFixed(2)}  ` +
        `spent $${(w.lifetime_spend_cents / 100).toFixed(2)}`
    );
  }

  console.log('\n✅ Seed complete.\n');
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(`\n❌ Seed failed: ${err.message}`);
    if (err.code) console.error(`   code: ${err.code}`);
    if (err.detail) console.error(`   detail: ${err.detail}`);
    console.error('');
    process.exit(1);
  });
